import { CustomForm, FormSubmission } from '../types';

export const INITIAL_CUSTOM_FORMS: CustomForm[] = [
  {
    id: 'frm-001',
    code: 'FRM-HSE-001',
    title: 'Checklist Inspeksi K3 & Safety Patrol Harian',
    category: 'K3 & Keselamatan Kerja',
    description:
      'Pemeriksaan kepatuhan APD pekerja, proteksi ketinggian, kondisi perancah/scaffolding, ketersediaan APAR, dan mitigasi unsafe act/condition di area proyek.',
    icon: 'ShieldCheck',
    version: 1,
    status: 'Active',
    createdBy: 'Hendra Setiawan, ST (Site Manager)',
    createdAt: '2026-08-01 08:30',
    updatedAt: '2026-08-15 09:00',
    requireSignature: true,
    requirePhoto: true,
    targetApproverRole: 'Site Manager',
    fields: [
      {
        id: 'sec_meta',
        label: 'Lingkup Pengawasan Lapangan',
        type: 'heading',
        required: false,
      },
      {
        id: 'tgl_inspeksi',
        label: 'Tanggal & Waktu Inspeksi',
        type: 'date',
        required: true,
        defaultValue: '2026-09-18',
      },
      {
        id: 'zona_kerja',
        label: 'Area / Zona Kerja yang Diinspeksi',
        type: 'text',
        placeholder: 'Contoh: Lantai 8 Zona Barat & Void Lift',
        required: true,
      },
      {
        id: 'nama_inspektur',
        label: 'Nama Petugas K3 / Safety Officer',
        type: 'text',
        placeholder: 'Contoh: Fajar Pratama, S.Tr.T (HSE)',
        required: true,
      },
      {
        id: 'jml_pekerja',
        label: 'Jumlah Pekerja Aktif di Zona Tersebut',
        type: 'number',
        unit: 'Orang',
        required: true,
      },
      {
        id: 'sec_checklist',
        label: 'Parameter Pemeriksaan Keselamatan',
        type: 'heading',
        required: false,
      },
      {
        id: 'cek_apd',
        label: '1. Kepatuhan APD Wajib (Helm, Rompi, Sepatu Safety, Kacamata)',
        type: 'condition',
        options: ['Lengkap & Patuh', 'Sebagian Tidak Pakai', 'Pelanggaran Kritis'],
        required: true,
      },
      {
        id: 'cek_scaffolding',
        label: '2. Kelayakan Perancah / Scaffolding & Pipa Penopang',
        type: 'condition',
        options: ['Aman & Ada Safety Tag Hijau', 'Perlu Perbaikan Pipa/Clamp', 'Dilarang Pakai (Tag Merah)'],
        required: true,
      },
      {
        id: 'cek_void',
        label: '3. Barikade Pengaman Void & Tepi Bangunan (Fall Protection)',
        type: 'condition',
        options: ['Terpasang Kokoh & Rapi', 'Kurang Memadai', 'Terbuka / Bahaya Jatuh'],
        required: true,
      },
      {
        id: 'cek_apar',
        label: '4. Kesiapan Alat Pemadam Api (APAR) & Kotak P3K',
        type: 'condition',
        options: ['Siap Pakai & Bertekanan Normal', 'Kadaluarsa / Perlu Refill', 'Tidak Ditemukan'],
        required: true,
      },
      {
        id: 'sec_temuan',
        label: 'Evaluasi & Tindakan Mitigasi',
        type: 'heading',
        required: false,
      },
      {
        id: 'catatan_temuan',
        label: 'Deskripsi Temuan Khusus / Tindakan Tidak Aman (Unsafe Act)',
        type: 'textarea',
        placeholder: 'Tuliskan temuan jika ada pekerja tidak memakai safety harness di ketinggian >2 meter atau material berserakan...',
        required: false,
      },
      {
        id: 'tindakan_koreksi',
        label: 'Tindakan Koreksi Cepat yang Langsung Diberikan',
        type: 'textarea',
        placeholder: 'Tindakan yang telah diambil di tempat saat patroli berlangsung...',
        required: false,
      },
      {
        id: 'skor_k3',
        label: 'Indeks Kepatuhan K3 Zona Ini (Skor 1 - 5)',
        type: 'rating',
        required: true,
      },
      {
        id: 'foto_inspeksi',
        label: 'Foto Dokumentasi Patroli K3',
        type: 'photo',
        required: true,
        helpText: 'Unggah foto kondisi perancah, pekerja, atau temuan lapangan.',
      },
      {
        id: 'ttd_petugas',
        label: 'Tanda Tangan Digital Pengawas K3',
        type: 'signature',
        required: true,
      },
    ],
  },
  {
    id: 'frm-002',
    code: 'FRM-QC-002',
    title: 'Ceklist Izin Pengecoran & Uji Slump Beton',
    category: 'Mutu & Quality Control',
    description:
      'Formulir persetujuan pengecoran struktur beton, verifikasi kesiapan pembesian dan bekisting, pengujian slump beton segar, dan pengambilan sampel silinder.',
    icon: 'CheckCircle2',
    version: 1,
    status: 'Active',
    createdBy: 'Ir. Budi Santoso, MT (Project Manager)',
    createdAt: '2026-08-02 10:15',
    updatedAt: '2026-08-20 11:30',
    requireSignature: true,
    requirePhoto: true,
    targetApproverRole: 'Project Manager',
    fields: [
      {
        id: 'sec_spek',
        label: 'Spesifikasi Teknis Elemen Beton',
        type: 'heading',
        required: false,
      },
      {
        id: 'elemen_struktur',
        label: 'Elemen Struktur yang Dicor',
        type: 'text',
        placeholder: 'Contoh: Balok B1 & Plat Lantai 6 Zona 2',
        required: true,
      },
      {
        id: 'mutu_beton',
        label: 'Mutu Beton Rencana (fc / Karakteristik)',
        type: 'text',
        placeholder: 'Contoh: fc 30 MPa (K-350) NFA',
        required: true,
      },
      {
        id: 'vendor_batching',
        label: 'Nama Batching Plant / Vendor Ready Mix',
        type: 'text',
        placeholder: 'Contoh: PT Pionirbeton Industri Unit Pluit',
        required: true,
      },
      {
        id: 'vol_rencana',
        label: 'Estimasi Volume Pengecoran',
        type: 'number',
        unit: 'm3',
        required: true,
      },
      {
        id: 'sec_uji',
        label: 'Pemeriksaan Lapangan & Pengujian Beton',
        type: 'heading',
        required: false,
      },
      {
        id: 'cek_tulangan',
        label: '1. Kerapian Pembesian, Overlap & Selimut Beton (Beton Decking)',
        type: 'condition',
        options: ['Sesuai Gambar Kerja (Pass)', 'Ada Koreksi Minor', 'Tidak Layak (Fail)'],
        required: true,
      },
      {
        id: 'cek_bekisting',
        label: '2. Kekuatan Formwork / Bekisting & Kelurusan Dimensi',
        type: 'condition',
        options: ['Kokoh & Kedap Air', 'Perlu Penguat Tambahan', 'Bocor / Melendut'],
        required: true,
      },
      {
        id: 'nilai_slump',
        label: 'Nilai Slump Test yang Didapatkan',
        type: 'number',
        unit: 'cm',
        placeholder: 'Toleransi 12 ± 2 cm',
        required: true,
      },
      {
        id: 'suhu_beton',
        label: 'Suhu Beton Segar saat Tiba',
        type: 'number',
        unit: '°C',
        placeholder: 'Maks. 32°C',
        required: false,
      },
      {
        id: 'jml_silinder',
        label: 'Jumlah Sampel Benda Uji Silinder Diambil',
        type: 'number',
        unit: 'Silinder',
        placeholder: 'Contoh: 6 sampel (7, 14, 28 hari)',
        required: true,
      },
      {
        id: 'keputusan_izin',
        label: 'Keputusan Kelayakan Izin Tuang Cor',
        type: 'select',
        options: ['DISETUJUI (Boleh Mulai Pengecoran)', 'DISETUJUI DENGAN CATATAN', 'DITOLAK (Truk Dipulangkan)'],
        required: true,
      },
      {
        id: 'catatan_qc',
        label: 'Catatan Pengawas Mutu / Konsultan MK',
        type: 'textarea',
        placeholder: 'Tuliskan instruksi vibrator beton, curing compound, atau antisipasi cuaca...',
        required: false,
      },
      {
        id: 'foto_slump',
        label: 'Foto Pengujian Slump Test & Tuang Cor',
        type: 'photo',
        required: true,
      },
      {
        id: 'ttd_qc',
        label: 'Tanda Tangan QC Engineer Proyek',
        type: 'signature',
        required: true,
      },
    ],
  },
  {
    id: 'frm-003',
    code: 'FRM-OPS-003',
    title: 'Laporan Harian Fisik Lapangan (Daily Site Log)',
    category: 'Operasional & Laporan Lapangan',
    description:
      'Pencatatan harian progres pelaksanaan on-site, kehadiran tukang, kondisi cuaca, material masuk, dan kendala pekerjaan konstruksi.',
    icon: 'ClipboardList',
    version: 1,
    status: 'Active',
    createdBy: 'Hendra Setiawan, ST (Site Manager)',
    createdAt: '2026-08-05 14:00',
    updatedAt: '2026-08-25 17:00',
    requireSignature: true,
    requirePhoto: true,
    targetApproverRole: 'Site Manager',
    fields: [
      {
        id: 'sec_info',
        label: 'Informasi Tanggal & Waktu',
        type: 'heading',
        required: false,
      },
      {
        id: 'tgl_kerja',
        label: 'Tanggal Hari Kerja',
        type: 'date',
        required: true,
        defaultValue: '2026-09-18',
      },
      {
        id: 'cuaca_harian',
        label: 'Kondisi Cuaca Lapangan',
        type: 'select',
        options: [
          'Cerah Sepanjang Hari',
          'Berawan / Mendung Sebagian',
          'Hujan Ringan (Kerja Tetap Berjalan)',
          'Hujan Deras / Badai (Pekerjaan Terhenti)',
        ],
        required: true,
      },
      {
        id: 'jam_efektif',
        label: 'Total Jam Kerja Efektif On-Site',
        type: 'number',
        unit: 'Jam',
        placeholder: 'Standar 8 jam normal',
        required: true,
      },
      {
        id: 'sec_tenaga',
        label: 'Rekapitulasi Tenaga Kerja Mandor & Tukang',
        type: 'heading',
        required: false,
      },
      {
        id: 'jml_mandor',
        label: 'Jumlah Mandor / Kepala Regu',
        type: 'number',
        unit: 'Orang',
        required: true,
      },
      {
        id: 'jml_tukang',
        label: 'Jumlah Tukang Spesialis (Batu, Besi, Kayu, Mekanikal)',
        type: 'number',
        unit: 'Orang',
        required: true,
      },
      {
        id: 'jml_pekerja_lap',
        label: 'Jumlah Pekerja Kasar / Helper Lapangan',
        type: 'number',
        unit: 'Orang',
        required: true,
      },
      {
        id: 'sec_progress',
        label: 'Rincian Realisasi Pekerjaan Hari Ini',
        type: 'heading',
        required: false,
      },
      {
        id: 'uraian_pekerjaan',
        label: 'Uraian Detail Pekerjaan yang Telah Diselesaikan',
        type: 'textarea',
        placeholder: '1. Pemasangan begel balok as 4-8 lantai 8 selesai 100%\n2. Pengecatan dasar cat primer dinding kamar hotel lantai 4 (12 unit)\n3. Instalasi pipa conduit listrik zona barat',
        required: true,
      },
      {
        id: 'material_masuk',
        label: 'Material Konstruksi yang Masuk ke Proyek Hari Ini',
        type: 'textarea',
        placeholder: 'Contoh: Pasir cor 2 dump truck (16 m3), Besi D16 KS 200 batang, Kawat bendrat 5 roll',
        required: false,
      },
      {
        id: 'kendala_lapangan',
        label: 'Kendala / Hambatan Pekerjaan yang Dihadapi',
        type: 'textarea',
        placeholder: 'Contoh: Listrik PLN sempat padam selama 45 menit dari pukul 14.15 - 15.00...',
        required: false,
      },
      {
        id: 'rencana_besok',
        label: 'Target Rencana Kerja untuk Hari Esok',
        type: 'textarea',
        placeholder: 'Persiapan uji slump dan pengecoran plat lantai 8 pada pukul 10.00 pagi...',
        required: false,
      },
      {
        id: 'foto_progres',
        label: 'Dokumentasi Foto Pekerjaan Hari Ini',
        type: 'photo',
        required: true,
      },
      {
        id: 'ttd_pelaksana',
        label: 'Tanda Tangan Pelaksana Proyek',
        type: 'signature',
        required: true,
      },
    ],
  },
  {
    id: 'frm-004',
    code: 'FRM-LOG-004',
    title: 'Surat Permintaan Pengadaan Material (Material Requisition)',
    category: 'Logistik & Material',
    description:
      'Pengajuan resmi permintaan pembelian material bahan bangunan dari site manager kepada departemen purchasing / logistik kantor pusat.',
    icon: 'PackageSearch',
    version: 1,
    status: 'Active',
    createdBy: 'Siska (Purchasing & Supply Chain)',
    createdAt: '2026-08-08 11:00',
    updatedAt: '2026-09-01 09:30',
    requireSignature: true,
    requirePhoto: false,
    targetApproverRole: 'Purchasing',
    fields: [
      {
        id: 'sec_req',
        label: 'Data Pengajuan & Prioritas',
        type: 'heading',
        required: false,
      },
      {
        id: 'tgl_request',
        label: 'Tanggal Pengajuan',
        type: 'date',
        required: true,
        defaultValue: '2026-09-18',
      },
      {
        id: 'urgensi',
        label: 'Tingkat Prioritas Kebutuhan',
        type: 'select',
        options: ['Normal (Sesuai Jadwal Proyek)', 'Mendesak (Dibutuhkan Segera 1-2 Hari)', 'Emergency (Pekerjaan Lapangan Terancam Berhenti)'],
        required: true,
      },
      {
        id: 'nama_material',
        label: 'Nama Spesifik Material / Barang',
        type: 'text',
        placeholder: 'Contoh: Semen Portland Composite PCC 50 Kg SNI',
        required: true,
      },
      {
        id: 'merk_rekomendasi',
        label: 'Merk / Spesifikasi yang Direkomendasikan',
        type: 'text',
        placeholder: 'Contoh: Semen Gresik / Tiga Roda',
        required: false,
      },
      {
        id: 'kuantitas',
        label: 'Jumlah Kebutuhan (Volume)',
        type: 'number',
        required: true,
      },
      {
        id: 'satuan_brg',
        label: 'Satuan',
        type: 'text',
        placeholder: 'Contoh: Zak, Batang, Lembar, m3, Ton, Roll',
        required: true,
      },
      {
        id: 'est_biaya',
        label: 'Estimasi Anggaran Total Biaya (Rp)',
        type: 'currency',
        placeholder: 'Contoh: 18500000',
        required: false,
      },
      {
        id: 'tgl_dibutuhkan',
        label: 'Target Tanggal Material Harus Tiba di Lokasi',
        type: 'date',
        required: true,
      },
      {
        id: 'alasan_kebutuhan',
        label: 'Alasan Penggunaan & Referensi Pekerjaan',
        type: 'textarea',
        placeholder: 'Untuk pengecoran balok struktural lantai 7 sesuai master schedule pekan ke-46...',
        required: true,
      },
      {
        id: 'ttd_pemohon',
        label: 'Tanda Tangan Pemohon (Site Logistics / Site Manager)',
        type: 'signature',
        required: true,
      },
    ],
  },
  {
    id: 'frm-005',
    code: 'FRM-EQP-005',
    title: 'Inspeksi Harian & Berita Acara Kerusakan Alat Berat',
    category: 'Alat Berat & Fleet',
    description:
      'Pemeriksaan jam kerja (hour meter), kelayakan mesin hidrolik, sistem rem, dan pelaporan anomali kerusakan unit excavator, crane, atau dump truck.',
    icon: 'Truck',
    version: 1,
    status: 'Active',
    createdBy: 'Ir. Budi Santoso, MT',
    createdAt: '2026-08-10 13:00',
    updatedAt: '2026-09-02 10:00',
    requireSignature: true,
    requirePhoto: true,
    targetApproverRole: 'Equipment',
    fields: [
      {
        id: 'sec_unit',
        label: 'Data Unit & Operator',
        type: 'heading',
        required: false,
      },
      {
        id: 'nama_alat',
        label: 'Jenis & Model Alat Berat',
        type: 'select',
        options: [
          'Excavator Komatsu PC200-8',
          'Tower Crane Zoomlion TC5013',
          'Dump Truck Hino 500 FM 260 Ti',
          'Mobile Crane Kato KR-25H 25T',
          'Genset Silent Cummins 150 kVA',
          'Vibro Roller Sakai SV512TF 10T',
        ],
        required: true,
      },
      {
        id: 'kode_alat',
        label: 'Nomor Plat / Kode Lambung Unit',
        type: 'text',
        placeholder: 'Contoh: EXC-01 / B 9421 KTY',
        required: true,
      },
      {
        id: 'nama_operator',
        label: 'Nama Operator yang Mengoperasikan',
        type: 'text',
        placeholder: 'Contoh: Slamet Riyadi (SIO Migas Aktif)',
        required: true,
      },
      {
        id: 'hour_meter',
        label: 'Hour Meter (HM) / Odometer Terakhir',
        type: 'number',
        unit: 'Jam Kerja',
        required: true,
      },
      {
        id: 'sec_cek',
        label: 'Pengecekan Komponen Kritis',
        type: 'heading',
        required: false,
      },
      {
        id: 'oli_mesin',
        label: '1. Level Oli Mesin & Tekanan Oli Hidrolik',
        type: 'condition',
        options: ['Normal & Bersih', 'Kurang (Perlu Top-Up)', 'Bocor / Kritis'],
        required: true,
      },
      {
        id: 'rem_kemudi',
        label: '2. Fungsi Rem, Sistem Kemudi & Suspensi/Track',
        type: 'condition',
        options: ['Berfungsi Sempurna', 'Ada Bunyi / Getaran', 'Rusak / Blong'],
        required: true,
      },
      {
        id: 'status_operasi',
        label: '3. Kesimpulan Status Kelayakan Operasi',
        type: 'select',
        options: [
          'LAYAK BEROPERASI (Optimal)',
          'OPERASI DENGAN PENGAWASAN (Segera Dijadwalkan Servis)',
          'BREAKDOWN / DILARANG OPERASI (Perlu Derek / Teknisi)',
        ],
        required: true,
      },
      {
        id: 'gejala_kerusakan',
        label: 'Deskripsi Kerusakan / Indikasi Masalah',
        type: 'textarea',
        placeholder: 'Tuliskan jika terdapat suara knocking mesin, asap hitam pekat, atau tuas hidrolik berat...',
        required: false,
      },
      {
        id: 'est_servis',
        label: 'Estimasi Biaya Perbaikan / Sparepart (Rp)',
        type: 'currency',
        placeholder: 'Jika memerlukan penggantian sparepart',
        required: false,
      },
      {
        id: 'foto_alat',
        label: 'Foto Fisik Alat / Bagian yang Rusak',
        type: 'photo',
        required: false,
      },
      {
        id: 'ttd_operator',
        label: 'Tanda Tangan Operator / Mekanik Site',
        type: 'signature',
        required: true,
      },
    ],
  },
  {
    id: 'frm-006',
    code: 'FRM-FIN-006',
    title: 'Pengajuan Kas Bon & Kas Kecil Lapangan (Petty Cash)',
    category: 'Keuangan & Kas Bon',
    description:
      'Permohonan pencairan kas operasional lapangan untuk pembelian kebutuhan darurat, konsumsi lembur pekerja, BBM alat, dan koordinasi lingkungan.',
    icon: 'Wallet',
    version: 1,
    status: 'Active',
    createdBy: 'Novia (Finance & Accounting)',
    createdAt: '2026-08-12 09:00',
    updatedAt: '2026-09-05 15:00',
    requireSignature: true,
    requirePhoto: true,
    targetApproverRole: 'Finance',
    fields: [
      {
        id: 'sec_dana',
        label: 'Data Permohonan Dana Kas Bon',
        type: 'heading',
        required: false,
      },
      {
        id: 'tgl_bon',
        label: 'Tanggal Pengajuan',
        type: 'date',
        required: true,
        defaultValue: '2026-09-18',
      },
      {
        id: 'nama_pemohon_bon',
        label: 'Nama Lengkap Pemohon',
        type: 'text',
        placeholder: 'Contoh: Hendra Setiawan (Site Manager)',
        required: true,
      },
      {
        id: 'kategori_dana',
        label: 'Kategori Pengeluaran',
        type: 'select',
        options: [
          'BBM Solar / Bensin Alat & Operasional Proyek',
          'Uang Makan & Konsumsi Lembur Mandor/Pekerja',
          'Pembelian Perkakas Kerja Darurat (Mata Bor, Paku, Sarung Tangan)',
          'Biaya Koordinasi Lingkungan & Retribusi Lapangan',
          'Transportasi & Logistik Mendesak',
          'Lain-Lain Kebutuhan Operasional',
        ],
        required: true,
      },
      {
        id: 'nominal_bon',
        label: 'Nominal Dana yang Diajukan (Rp)',
        type: 'currency',
        placeholder: 'Contoh: 3500000',
        required: true,
      },
      {
        id: 'rekening_tujuan',
        label: 'Bank & Nomor Rekening Penerima Transfer',
        type: 'text',
        placeholder: 'Contoh: Bank BCA 8820192831 a/n Hendra Setiawan',
        required: true,
      },
      {
        id: 'rincian_kebutuhan',
        label: 'Rincian Penggunaan Dana & Justifikasi',
        type: 'textarea',
        placeholder: 'BBM Solar 250 liter untuk genset site saat lembur cor malam hari lantai 8...',
        required: true,
      },
      {
        id: 'foto_bukti_bon',
        label: 'Foto Nota / Estimasi Kwitansi / Bukti Pembelian',
        type: 'photo',
        required: false,
      },
      {
        id: 'ttd_pemohon_bon',
        label: 'Tanda Tangan Pemohon Kas Bon',
        type: 'signature',
        required: true,
      },
    ],
  },
];

export const INITIAL_FORM_SUBMISSIONS: FormSubmission[] = [
  {
    id: 'sub-001',
    submissionNumber: 'SUB/2026/09/001',
    formId: 'frm-001',
    formCode: 'FRM-HSE-001',
    formTitle: 'Checklist Inspeksi K3 & Safety Patrol Harian',
    formCategory: 'K3 & Keselamatan Kerja',
    projectId: 'prj-001',
    projectName: 'Pembangunan Gedung Perkantoran Wisma Utama 12 Lantai',
    location: 'Lantai 8 Zona Barat & Area Void Lift Utama',
    submittedBy: 'Fajar Pratama, S.Tr.T',
    submittedByRole: 'Supervisor K3 / HSE Officer',
    submittedByEmail: 'fajar.hse@rakaciptaseraya.co.id',
    submittedAt: '2026-09-18 09:45',
    status: 'Approved',
    reviewedBy: 'Hendra Setiawan, ST (Site Manager)',
    reviewedAt: '2026-09-18 11:20',
    reviewNotes: 'Temuan telah ditindaklanjuti. Pengaman void telah dipasang barikade kayu lapis cat kuning hitam.',
    values: {
      tgl_inspeksi: '2026-09-18',
      zona_kerja: 'Lantai 8 Zona Barat & Area Void Lift',
      nama_inspektur: 'Fajar Pratama, S.Tr.T',
      jml_pekerja: 42,
      cek_apd: 'Lengkap & Patuh',
      cek_scaffolding: 'Aman & Ada Safety Tag Hijau',
      cek_void: 'Terpasang Kokoh & Rapi',
      cek_apar: 'Siap Pakai & Bertekanan Normal',
      catatan_temuan: '3 pekerja pembesian sempat melepas kacamata pelindung karena debu, telah ditegur dan diarahkan memakai face shield.',
      tindakan_koreksi: 'Safety briefing singkat dilakukan di tempat dan pembagian kacamata cadangan.',
      skor_k3: 5,
      foto_inspeksi: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156f?w=600&auto=format&fit=crop&q=80',
    },
    signatures: [
      {
        role: 'Pengawas K3 Lapangan',
        name: 'Fajar Pratama, S.Tr.T',
        title: 'HSE Safety Officer',
        signedAt: '2026-09-18 09:45',
      },
      {
        role: 'Site Manager',
        name: 'Hendra Setiawan, ST',
        title: 'Penanggung Jawab Lapangan',
        signedAt: '2026-09-18 11:20',
      },
    ],
    photos: [
      {
        id: 'pho-01',
        caption: 'Pemasangan barikade void lift dan pekerja patuh memakai full body harness',
        dataUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156f?w=600&auto=format&fit=crop&q=80',
        timestamp: '2026-09-18 09:30',
      },
    ],
  },
  {
    id: 'sub-002',
    submissionNumber: 'SUB/2026/09/002',
    formId: 'frm-002',
    formCode: 'FRM-QC-002',
    formTitle: 'Ceklist Izin Pengecoran & Uji Slump Beton',
    formCategory: 'Mutu & Quality Control',
    projectId: 'prj-001',
    projectName: 'Pembangunan Gedung Perkantoran Wisma Utama 12 Lantai',
    location: 'Balok B1 & Plat Lantai 8 Zona 2',
    submittedBy: 'Dimas Wicaksono, ST',
    submittedByRole: 'QC Engineer',
    submittedByEmail: 'dimas.qc@rakaciptaseraya.co.id',
    submittedAt: '2026-09-17 14:15',
    status: 'Approved',
    reviewedBy: 'Ir. Budi Santoso, MT (Project Manager)',
    reviewedAt: '2026-09-17 14:40',
    reviewNotes: 'Hasil slump 12.5 cm berada dalam batas toleransi rencana. Izin tuang disetujui penuh.',
    values: {
      elemen_struktur: 'Balok B1 & Plat Lantai 8 Zona 2',
      mutu_beton: 'fc 30 MPa (K-350) Sikament Ready Mix',
      vendor_batching: 'PT Pionirbeton Industri Unit Pluit',
      vol_rencana: 48,
      cek_tulangan: 'Sesuai Gambar Kerja (Pass)',
      cek_bekisting: 'Kokoh & Kedap Air',
      nilai_slump: 12.5,
      suhu_beton: 29.5,
      jml_silinder: 6,
      keputusan_izin: 'DISETUJUI (Boleh Mulai Pengecoran)',
      catatan_qc: 'Pengecoran dilakukan bertahap menggunakan concrete pump. Vibrator beton disiagakan 2 unit cadangan.',
      foto_slump: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
    },
    signatures: [
      {
        role: 'QC Inspector',
        name: 'Dimas Wicaksono, ST',
        title: 'Quality Control Engineer',
        signedAt: '2026-09-17 14:15',
      },
      {
        role: 'Konsultan Pengawas / PM',
        name: 'Ir. Budi Santoso, MT',
        title: 'Project Manager',
        signedAt: '2026-09-17 14:40',
      },
    ],
    photos: [
      {
        id: 'pho-02',
        caption: 'Uji slump test sampel beton mixer truk ke-1: 12.5 cm sesuai spesifikasi RKS',
        dataUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
        timestamp: '2026-09-17 14:10',
      },
    ],
  },
  {
    id: 'sub-003',
    submissionNumber: 'SUB/2026/09/003',
    formId: 'frm-003',
    formCode: 'FRM-OPS-003',
    formTitle: 'Laporan Harian Fisik Lapangan (Daily Site Log)',
    formCategory: 'Operasional & Laporan Lapangan',
    projectId: 'prj-002',
    projectName: 'Pekerjaan Jembatan Beton Precast & Akses Tol KM 42',
    location: 'Abutment 2 & Pier Head Jembatan Tol',
    submittedBy: 'Hendra Setiawan, ST',
    submittedByRole: 'Site Manager',
    submittedByEmail: 'hendra.site@rakaciptaseraya.co.id',
    submittedAt: '2026-09-17 17:30',
    status: 'In Review',
    values: {
      tgl_kerja: '2026-09-17',
      cuaca_harian: 'Cerah Sepanjang Hari',
      jam_efektif: 9,
      jml_mandor: 3,
      jml_tukang: 28,
      jml_pekerja_lap: 18,
      uraian_pekerjaan: '1. Erection girder precast bentang 30m unit ke-4 dan ke-5 berhasil terpasang di atas Pier Head 2\n2. Pemasangan perancah falsework bentang lanjutan\n3. Pengelasan sambungan bearing pad elastomeric',
      material_masuk: 'Girder Precast I-Beam 30m (2 unit), Angkur baja dia 32mm (40 pcs)',
      kendala_lapangan: 'Lalu lintas jalan arteri di bawah jembatan sempat padat saat manuver mobile crane 100T, telah dikoordinasikan dengan Polantas setempat.',
      rencana_besok: 'Penyelesaian stressing kabel strand tendon bentang 4 dan grouting semen non-shrink.',
      foto_progres: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    },
    signatures: [
      {
        role: 'Pelaksana Proyek',
        name: 'Hendra Setiawan, ST',
        title: 'Site Manager',
        signedAt: '2026-09-17 17:30',
      },
    ],
    photos: [
      {
        id: 'pho-03',
        caption: 'Proses erection girder precast unit ke-5 dengan tandem mobile crane berjalan aman',
        dataUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
        timestamp: '2026-09-17 16:00',
      },
    ],
  },
  {
    id: 'sub-004',
    submissionNumber: 'SUB/2026/09/004',
    formId: 'frm-004',
    formCode: 'FRM-LOG-004',
    formTitle: 'Surat Permintaan Pengadaan Material (Material Requisition)',
    formCategory: 'Logistik & Material',
    projectId: 'prj-001',
    projectName: 'Pembangunan Gedung Perkantoran Wisma Utama 12 Lantai',
    location: 'Gudang Material Proyek Jakarta Selatan',
    submittedBy: 'Andi Nugroho',
    submittedByRole: 'Logistik Proyek',
    submittedByEmail: 'andi.logistik@rakaciptaseraya.co.id',
    submittedAt: '2026-09-18 10:15',
    status: 'Submitted',
    values: {
      tgl_request: '2026-09-18',
      urgensi: 'Mendesak (Dibutuhkan Segera 1-2 Hari)',
      nama_material: 'Semen Portland Composite PCC 50 Kg',
      merk_rekomendasi: 'Semen Gresik SNI',
      kuantitas: 400,
      satuan_brg: 'Zak',
      est_biaya: 26000000,
      tgl_dibutuhkan: '2026-09-20',
      alasan_kebutuhan: 'Stok gudang tersisa 35 zak. Diperlukan untuk pekerjaan plesteran dan acian dinding lantai 5 dan 6.',
    },
    signatures: [
      {
        role: 'Petugas Logistik Lapangan',
        name: 'Andi Nugroho',
        title: 'Site Logistics Officer',
        signedAt: '2026-09-18 10:15',
      },
    ],
    photos: [],
  },
];
