import { OfficialLetter, LetterTemplate, BastDocument } from '../types';

export const INITIAL_LETTER_TEMPLATES: LetterTemplate[] = [
  {
    id: 'TPL-SPK',
    name: 'Surat Perintah Kerja (SPK) Subkon / Mitra',
    category: 'SPK',
    description: 'Format penerbitan perintah kerja proyek, lingkup pengerjaan, nilai kontrak, dan termin.',
    defaultTitle: 'Surat Perintah Kerja (SPK) Pelaksanaan Pekerjaan Proyek',
    defaultSubject: 'Surat Perintah Kerja (SPK)',
    defaultEnclosure: '1 (satu) Berkas Lampiran Spesifikasi Teknis',
    defaultOpeningText: 'Dengan hormat,\nSehubungan dengan kesepakatan hasil pembahasan teknis dan komersial, PT Raka Cipta Seraya memberikan Surat Perintah Kerja (SPK) kepada:',
    defaultBodyText:
      '1. Lingkup Pekerjaan: Pelaksanaan pengerjaan konstruksi/pemasangan material proyek sesuai spesifikasi.\n' +
      '2. Nilai Pekerjaan: Sebesar Rp 250.000.000,- (Dua Ratus Lima Puluh Juta Rupiah) belum termasuk PPN.\n' +
      '3. Waktu Pelaksanaan: 45 (empat puluh lima) hari kalender terhitung sejak penerbitan SPK ini.\n' +
      '4. Syarat Pembayaran: Pembayaran berbasis termin progress fisik pekerjaan yang disetujui Pengawas Proyek.',
    defaultClosingText: 'Demikian Surat Perintah Kerja ini dibuat untuk dilaksanakan sebagaimana mestinya dengan penuh rasa tanggung jawab.',
    defaultSignatoryTitle: 'Direktur Utama',
    isSystemDefault: true,
    createdAt: '2026-07-31T00:00:00Z',
  },
  {
    id: 'TPL-SPH',
    name: 'Surat Penawaran Harga (SPH / Commercial Offer)',
    category: 'SPH',
    description: 'Format penawaran harga resmi pengadaan material, barang, atau jasa proyek.',
    defaultTitle: 'Surat Penawaran Harga (SPH)',
    defaultSubject: 'Penawaran Harga Pekerjaan & Supplai Material Proyek',
    defaultEnclosure: '1 (satu) Berkas RAB Penawaran',
    defaultOpeningText: 'Dengan hormat,\nMerujuk pada permintaan penawaran harga (RFP) dari pihak Bapak/Ibu, bersama surat ini kami mengajukan rincian penawaran harga sebagai berikut:',
    defaultBodyText:
      '1. Rincian Pekerjaan: Pengadaan material beton, besi ulir, dan jasa pengerjaan struktur.\n' +
      '2. Total Harga Penawaran: Rp 850.000.000,- (Delapan Ratus Lima Puluh Juta Rupiah) inc. PPN.\n' +
      '3. Masa Berlaku Penawaran: Berlaku selama 30 (tiga puluh) hari kalender sejak tanggal penerbitan.\n' +
      '4. Metode Pembayaran: DP 20% saat pelimpahan PO, pelunasan sesuai progress kirim.',
    defaultClosingText: 'Besar harapan kami dapat bekerjasama dengan perusahaan Bapak/Ibu. Atas perhatiannya disampaikan terima kasih.',
    defaultSignatoryTitle: 'Manager Marketing & Tender',
    isSystemDefault: true,
    createdAt: '2026-07-31T00:00:00Z',
  },
  {
    id: 'TPL-SKK',
    name: 'Surat Keterangan Kerja (Employment Certificate)',
    category: 'SKK',
    description: 'Format keterangan resmi masa kerja karyawan untuk instansi / perbankan.',
    defaultTitle: 'Surat Keterangan Kerja (Employment Certificate)',
    defaultSubject: 'Surat Keterangan Kerja Karyawan',
    defaultEnclosure: '-',
    defaultOpeningText: 'Yang bertanda tangan di bawah ini, Management PT Raka Cipta Seraya menerangkan bahwa:',
    defaultBodyText:
      'Nama: [Nama Karyawan]\n' +
      'NIK / NIP: [Nomor Induk Karyawan]\n' +
      'Jabatan: [Jabatan Terakhir]\n' +
      'Masa Kerja: [Tanggal Mulai] s.d [Tanggal Selesai]\n' +
      'Bahwa yang bersangkutan adalah benar pernah bekerja pada perusahaan kami dengan dedikasi dan kinerja yang sangat baik.',
    defaultClosingText: 'Demikian surat keterangan kerja ini diberikan agar dapat dipergunakan sebagaimana mestinya.',
    defaultSignatoryTitle: 'Head of Human Resources Department',
    isSystemDefault: true,
    createdAt: '2026-07-31T00:00:00Z',
  },
  {
    id: 'TPL-SURAT-TUGAS',
    name: 'Surat Tugas Inspeksi & Penugasan Lapangan',
    category: 'SURAT_TUGAS',
    description: 'Format instruksi kerja lapangan untuk tim teknisi dan pengawas proyek.',
    defaultTitle: 'Surat Tugas Penugasan Lapangan Proyek',
    defaultSubject: 'Surat Tugas Supervision & Inspeksi Site',
    defaultEnclosure: '1 (satu) Berkas Surat Jalan',
    defaultOpeningText: 'Direksi PT Raka Cipta Seraya memberikan tugas resmi kepada personil di bawah ini:',
    defaultBodyText:
      '1. Nama / Jabatan: [Nama Personil] - Site Engineer / Project Manager.\n' +
      '2. Lokasi Penugasan: Proyek Pembangunan Gedung & Infrastruktur.\n' +
      '3. Waktu Penugasan: Berlaku mulai tanggal [Tanggal] s.d [Tanggal].\n' +
      '4. Tugas & Kewajiban: Melaksanakan pengawasan mutu teknis, koordinasi dengan subkontraktor, dan menyusun laporan progress mingguan.',
    defaultClosingText: 'Demikian Surat Tugas ini dibuat untuk dipergunakan dan dilaksanakan dengan sebaik-baiknya.',
    defaultSignatoryTitle: 'Manager Operasional',
    isSystemDefault: true,
    createdAt: '2026-07-31T00:00:00Z',
  },
  {
    id: 'TPL-UNDANGAN',
    name: 'Surat Undangan Rapat Evaluasi Proyek',
    category: 'UNDANGAN',
    description: 'Format undangan rapat koordinasi mingguan atau bulanan proyek.',
    defaultTitle: 'Surat Undangan Rapat Evaluasi Proyek',
    defaultSubject: 'Undangan Rapat Evaluasi & Coordination Meeting',
    defaultEnclosure: '1 (satu) Lembar Agenda Rapat',
    defaultOpeningText: 'Dengan hormat,\nDalam rangka koordinasi pelaksanaan pengerjaan proyek dan evaluasi progress bulanan, kami mengundang Bapak/Ibu untuk hadir pada rapat yang akan dilaksanakan pada:',
    defaultBodyText:
      'Hari / Tanggal: Senin, 10 Agustus 2026\nWaktu: Pukul 09.00 WIB - Selesai\nTempat: Ruang Rapat Utama PT Raka Cipta Seraya / Site Office Proyek\nAgenda Rapat: Evaluasi Progress Fisik, Review Material, dan Jadwal Kurva-S.',
    defaultClosingText: 'Mengingat pentingnya agenda rapat ini, kehadiran tepat waktu sangat kami harapkan. Atas perhatiannya kami ucapkan terima kasih.',
    defaultSignatoryTitle: 'Direktur Utama',
    isSystemDefault: true,
    createdAt: '2026-07-31T00:00:00Z',
  },
  {
    id: 'TPL-SP1',
    name: 'Surat Peringatan Pertama (SP-1) Kedisiplinan',
    category: 'SP',
    description: 'Format teguran tertulis kedisiplinan dan evaluasi tata tertib karyawan.',
    defaultTitle: 'Surat Peringatan Pertama (SP 1)',
    defaultSubject: 'Surat Peringatan Kedisiplinan Karyawan',
    defaultEnclosure: '-',
    defaultOpeningText: 'Surat Peringatan Pertama (SP-1) ini diterbitkan oleh Manajemen PT Raka Cipta Seraya kepada:',
    defaultBodyText:
      'Nama: [Nama Karyawan]\n' +
      'Jabatan: [Jabatan Karyawan]\n' +
      'Divisi: [Nama Divisi / Proyek]\n' +
      'Alasan Penerbitan: Berdasarkan evaluasi absensi & kedisiplinan kerja, saudara telah melakukan tindakan keterlambatan tanpa konfirmasi selama 3 hari berturut-turut.\n' +
      'Ketentuan SP-1: Surat Peringatan ini berlaku selama 6 (enam) bulan.',
    defaultClosingText: 'Demikian Surat Peringatan ini disampaikan agar menjadi perhatian serius dan bahan perbaikan kedisiplinan saudara.',
    defaultSignatoryTitle: 'Head of Human Resources Department',
    isSystemDefault: true,
    createdAt: '2026-07-31T00:00:00Z',
  },
];

export const INITIAL_OFFICIAL_LETTERS: OfficialLetter[] = [
  {
    id: 'LTR-001',
    letterNumber: '088/SPK/PT-RCS/VIII/2026',
    category: 'SPK',
    title: 'Surat Perintah Kerja (SPK) Subkontraktor Pembesian',
    subject: 'Surat Perintah Kerja Pelaksanaan Pembesian Struktur',
    enclosure: '1 (satu) Berkas Lampiran Spesifikasi Teknis',
    letterDate: '2026-08-01',
    city: 'Jakarta',
    recipientName: 'Ir. Budi Santoso',
    recipientTitle: 'Direktur Utama',
    recipientCompany: 'PT Baja Konstruksi Mandiri',
    recipientAddress: 'Jl. Industri Raya No. 45, Kawasan Cikarang, Bekasi',
    openingText: 'Dengan hormat,\nSehubungan dengan kesepakatan hasil negosiasi tender dan klarifikasi teknis pekerjaan proyek pembangunan gedung kantor, bersama surat ini PT Raka Cipta Seraya menugaskan pihak kedua:',
    bodyParagraphs: [
      '1. Lingkup Pekerjaan: Pelaksanaan pengerjaan fabrikasi & instalasi besi beton bertulang ulir D13-D25 sesuai gambar kerja proyek.',
      '2. Nilai Pekerjaan: Sebesar Rp 450.000.000,- (Empat Ratus Lima Puluh Juta Rupiah) belum termasuk PPN 11%.',
      '3. Jangka Waktu Pelaksanaan: Berlangsung selama 60 (enam puluh) hari kalender terhitung sejak tanggal 5 Agustus 2026 sampai dengan 4 Oktober 2026.',
      '4. Sistem Pembayaran: Pembayaran dilakukan secara bertahap (Termin Progress) sesuai prestasi fisik pekerjaan yang telah diverifikasi oleh Project Manager di lapangan.',
      '5. Syarat Keselamatan Kerja (K3): Pihak kedua wajib mematuhi seluruh standar K3L & APD lengkap selama berada di area proyek.'
    ],
    closingText: 'Demikian Surat Perintah Kerja ini diterbitkan untuk dilaksanakan dengan penuh rasa tanggung jawab. Atas perhatian dan kerjasamanya kami ucapkan terima kasih.',
    signatoryName: 'Ir. Raka Cipta Seraya, M.T.',
    signatoryTitle: 'Direktur Utama',
    signatoryNik: 'NIK. 19850412 201001 1 002',
    showStamp: true,
    showQrCode: true,
    qrCodeValue: 'https://verifikasi.rakaciptaseraya.co.id/verify?id=LTR-001&no=088%2FSPK%2FPT-RCS%2FVIII%2F2026',
    status: 'Diterbitkan',
    scannedAttachments: [
      {
        id: 'SCAN-001',
        title: 'Lampiran Fisik Kontrak & Spesifikasi Teknis Besi',
        scannedAt: '2026-08-01T14:30:00Z',
        dataUrl: 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=800&auto=format&fit=crop&q=80',
        pageNumber: 1,
        filterUsed: 'magic',
      },
    ],
    createdAt: '2026-07-30T10:00:00Z',
    updatedAt: '2026-07-30T10:00:00Z',
  },
  {
    id: 'LTR-002',
    letterNumber: '112/SPH/PT-RCS/VIII/2026',
    category: 'SPH',
    title: 'Surat Penawaran Harga Pekerjaan Infrastruktur Jalan',
    subject: 'Penawaran Harga Pekerjaan Pengaspalan & Drainase Proyek',
    enclosure: '1 (satu) Berkas BOQ & Rincian RAB',
    letterDate: '2026-08-02',
    city: 'Jakarta',
    recipientName: 'H. Ahmad Subagyo, S.E.',
    recipientTitle: 'Head of Procurement',
    recipientCompany: 'PT Nusantara Developers Tbk',
    recipientAddress: 'Gedung Menara Mandiri Lt. 18, Jl. Jend. Sudirman, Jakarta Selatan',
    openingText: 'Dengan hormat,\nMemenuhi undangan tender nomor 042/TND/ND/VII/2026 perihal Penawaran Pekerjaan Infrastruktur Jalan Proyek Kawasan Industri, kami dari PT Raka Cipta Seraya mengajukan penawaran harga sebagai berikut:',
    bodyParagraphs: [
      '1. Total Nilai Penawaran: Rp 1.250.000.000,- (Satu Miliar Dua Ratus Lima Puluh Juta Rupiah) inc. PPN.',
      '2. Masa Berlaku Penawaran: Penawaran harga ini berlaku selama 30 (tiga puluh) hari kalender terhitung sejak tanggal penerbitan surat ini.',
      '3. Garansi Pekerjaan: Garansi pemeliharaan pekerjaan diberikan selama 180 (seratus delapan puluh) hari kalender pasca BAST I.',
      '4. Lampiran Pendukung: Terlampir Rekapitulasi Rincian Anggaran Biaya (RAB), Spesifikasi Material Mix Asphalt Hotmix AC-WC, dan Analisa Harga Satuan Pekerjaan (AHSP).'
    ],
    closingText: 'Besar harapan kami untuk dapat berpartisipasi dan menjalin kemitraan profesional dalam proyek ini. Demikian penawaran ini kami sampaikan, atas perhatian Bapak/Ibu kami ucapkan terima kasih.',
    signatoryName: 'Dra. Hendra Wijaya',
    signatoryTitle: 'Manager Marketing & Tender',
    signatoryNik: 'NIK. 19880215 201203 1 005',
    showStamp: true,
    showQrCode: true,
    qrCodeValue: 'https://verifikasi.rakaciptaseraya.co.id/verify?id=LTR-002&no=112%2FSPH%2FPT-RCS%2FVIII%2F2026',
    status: 'Diterbitkan',
    createdAt: '2026-07-31T08:30:00Z',
    updatedAt: '2026-07-31T08:30:00Z',
  },
  {
    id: 'LTR-003',
    letterNumber: '045/SKK/HRD-RCS/VIII/2026',
    category: 'SKK',
    title: 'Surat Keterangan Kerja (Certificate of Employment)',
    subject: 'Surat Keterangan Pengalaman Kerja',
    enclosure: '-',
    letterDate: '2026-08-01',
    city: 'Jakarta',
    recipientName: 'Kepada Pihak Yang Berkepentingan',
    recipientTitle: 'Di Tempat',
    recipientCompany: '-',
    recipientAddress: 'Di Tempat',
    openingText: 'Yang bertanda tangan di bawah ini, Manajemen PT Raka Cipta Seraya menerangkan dengan sebenarnya bahwa:',
    bodyParagraphs: [
      'Nama: Muhammad Rizky Febrian, S.T.',
      'NIK Karyawan: EMP-2022-089',
      'Jabatan Terakhir: Site Supervisor / Pengawas Lapangan',
      'Masa Kerja: 10 Agustus 2022 s.d 31 Juli 2026',
      'Bahwa yang bersangkutan telah bekerja pada PT Raka Cipta Seraya dengan menunjukkan dedikasi, integritas, dan kontribusi kerja yang sangat baik dalam pengelolaan proyek-proyek konstruksi nasional.',
      'Surat Keterangan Kerja ini diterbitkan atas permintaan yang bersangkutan untuk dipergunakan sebagaimana mestinya.'
    ],
    closingText: 'Demikian surat keterangan ini dibuat agar dapat dipergunakan dengan sebaik-baiknya.',
    signatoryName: 'Siti Rahmawati, S.Psi.',
    signatoryTitle: 'Head of Human Resources Department',
    signatoryNik: 'NIK. 19910510 201502 2 001',
    showStamp: true,
    showQrCode: true,
    qrCodeValue: 'https://verifikasi.rakaciptaseraya.co.id/verify?id=LTR-003&no=045%2FSKK%2FHRD-RCS%2FVIII%2F2026',
    status: 'Diterbitkan',
    createdAt: '2026-07-31T09:00:00Z',
    updatedAt: '2026-07-31T09:00:00Z',
  },
];

export const INITIAL_BAST_DOCS: BastDocument[] = [
  {
    id: 'bast-001',
    type: 'BAST1',
    bastNumber: '015/BAST-1/RCS-PROJ/VIII/2026',
    projectId: '1',
    projectName: 'Pembangunan Gedung Perkantoran Wisma Utama 12 Lantai',
    clientName: 'PT Graha Jaya Utama',
    clientAddress: 'Jl. Jendral Sudirman No. 102, Jakarta Selatan',
    clientRepresentative: 'Ir. Hendra Kusuma',
    contractNumber: '008/SPK/GJU/III/2026',
    contractDate: '2026-03-10',
    contractValue: 2500000000,
    retentionPct: 5,
    retentionAmount: 125000000,
    bastDate: '2026-08-01',
    bastCity: 'Jakarta',
    maintenanceDays: 180,
    maintenanceEndDate: '2027-01-28',
    inspectionNotes:
      'Seluruh pekerjaan fisik struktur dan finishing telah selesai 100%. Testing commissioning genset dan AC central dinyatakan lulus dengan hasil sempurna.',
    status: 'Ditandatangani',
    contractorSignatory: 'Ir. Raka Cipta Seraya, M.T.',
    contractorTitle: 'Direktur Utama',
    clientSignatory: 'Ir. Hendra Kusuma',
    clientTitle: 'Project Director',
    consultantSignatory: 'Budi Santoso, S.T.',
    consultantTitle: 'Team Leader MK',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'bast-002',
    type: 'BAST2',
    bastNumber: '004/BAST-2/RCS-PROJ/VIII/2026',
    refBast1Number: '002/BAST-1/RCS-PROJ/02/2026',
    projectId: '2',
    projectName: 'Pekerjaan Jembatan Beton Precast & Akses Tol KM 42',
    clientName: 'PT Kuliner Nusantara',
    clientAddress: 'Jl. Cikini Raya No. 45, Jakarta Pusat',
    clientRepresentative: 'Dewi Sartika',
    contractNumber: '012/SPK/KN/I/2026',
    contractDate: '2026-01-15',
    contractValue: 850000000,
    retentionPct: 5,
    retentionAmount: 42500000,
    bastDate: '2026-08-05',
    bastCity: 'Jakarta',
    maintenanceDays: 180,
    maintenanceEndDate: '2026-08-05',
    inspectionNotes:
      'Masa pemeliharaan 180 hari telah berakhir. Seluruh poin checklist defect list telah diperbaiki dan dibersihkan 100%. Retensi 5% dapat dicairkan full.',
    status: 'Retensi Dicairkan',
    contractorSignatory: 'Ir. Raka Cipta Seraya, M.T.',
    contractorTitle: 'Direktur Utama',
    clientSignatory: 'Dewi Sartika',
    clientTitle: 'General Manager',
    createdAt: '2026-08-05T11:00:00Z',
    updatedAt: '2026-08-05T11:00:00Z',
  },
];
